using System;
using System.Collections.Generic;
using System.Text;
using System.Security.Cryptography;
using System.IO;

namespace EChestVC.Model
{
    /// <summary>
    /// Methods for computing the SHA256 hash
    /// </summary>
    static class Hash
    {
        //160 bits in a SHA1 hash -> 40 character hex string
        /// <summary>
        /// Returns the number of characters that should appear in a hex string generated by the hash
        /// </summary>
        public const int NumHexChars = 40;

        public static string ComputeHash(string input)
        {
            return ComputeHash(Encoding.ASCII.GetBytes(input));
        }

        public static string ComputeHash(byte[] input)
        {
            var hasher = SHA1.Create();
            hasher.ComputeHash(input);
            string hash = HashToHex(hasher);
            hasher.Dispose();
            return hash;
        }

        public static string ComputeHash(Stream input)
        {
            var hasher = SHA1.Create();
            hasher.ComputeHash(input);
            string hash = HashToHex(hasher);
            hasher.Dispose();
            return hash;
        }

        /// <summary>
        /// Returns the hash in the form of a hexadecimal string
        /// </summary>
        /// <param name="hasher"></param>
        /// <returns></returns>
        private static string HashToHex(HashAlgorithm hasher)
        {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < hasher.Hash.Length; i++)
            {
                sb.Append(hasher.Hash[i].ToString("x2"));
            }
            return sb.ToString();
        }
    }
}
